### ISSUE TITLE
sendCommand

### ISSUE THREAD

**Issue by TalpaRadioBramMolenaar** [Dev1an/Atem#8]
Hi,

When i try to use sendCommand i need to send a buffer. When I send one, I get: `TypeError: cmd.serialize is not a function`. What do I wrong, or is this a bug.

Thx.

**Comment by Dev1an** [comment]
Sorry, I didn't document that function. `Device#sendCommand` does not accept buffers, it only accepts [`Command`s](http://dev1an.github.io/Atem/Command.html). For an example on ho to use it, look at https://github.com/Dev1an/Atem/blob/22436f436687fcf54a84883b3c9a0c072d55f43a/index.js#L661-L674

**Comment by TalpaRadioBramMolenaar** [comment]
I tried, but I need a Command Class. and in my application i can't define a Command class.

**Comment by Dev1an** [comment]
You don't need to define a `Command` class yourself. Use the [`Command` class from my library](http://dev1an.github.io/Atem/Command.html):
```js
const Atem = require('atem')
const tvStudio = new Atem('10.1.0.3')

const data = new Buffer(4)
data.fill(0)
const doCut = new Atem.Command('DCut', data)
tvStudio.sendCommand(doCut)
```

**Comment by TalpaRadioBramMolenaar** [comment]
Ofcourse..... Thx for the help. It works!

**Comment by Dev1an** [comment]
Nice to hear it works for you. If you implement new functionality please contribute back to the community by sending a pull request with your additions.
